/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QTabWidget *tabWidgetTraversalEntityTypes;
    QWidget *tab;
    QLineEdit *inputEndCoords;
    QPushButton *buttonClearCoords;
    QLabel *labelAnimTypeHeader;
    QCheckBox *selectReciprocalTraversal;
    QPushButton *buttonGenerateTraversal;
    QGroupBox *groupBoxMonsterSelect;
    QCheckBox *demonSelect_15;
    QLabel *labelMonsterType_Heavy;
    QCheckBox *demonSelect_18;
    QCheckBox *demonSelect_14;
    QCheckBox *demonSelect_17;
    QCheckBox *demonSelect_12;
    QCheckBox *demonSelect_7;
    QCheckBox *demonSelect_19;
    QCheckBox *demonSelect_9;
    QCheckBox *demonSelect_3;
    QLabel *labelMonsterType_SHeavy;
    QCheckBox *demonSelect_10;
    QCheckBox *demonSelect_5;
    QCheckBox *demonSelect_21;
    QCheckBox *demonSelect_16;
    QCheckBox *demonSelect_13;
    QCheckBox *demonSelect_8;
    QCheckBox *demonSelect_22;
    QCheckBox *demonSelect_2;
    QCheckBox *demonSelect_1;
    QLabel *labelMonsterType_Fodder;
    QCheckBox *demonSelect_20;
    QCheckBox *demonSelect_6;
    QCheckBox *demonSelect_4;
    QCheckBox *demonSelect_11;
    QLabel *labelMonsterTypeHeader;
    QLabel *labelMonsterTypePresetInfo;
    QRadioButton *radioButtonPresetAInfo;
    QRadioButton *radioButtonPresetSuperHeavyInfo;
    QRadioButton *radioButtonPresetFodderInfo;
    QRadioButton *radioButtonPresetCInfo;
    QRadioButton *radioButtonPresetHeavyInfo;
    QRadioButton *radioButtonPresetNoneInfo;
    QRadioButton *radioButtonPresetBInfo;
    QRadioButton *radioButtonPresetDInfo;
    QComboBox *comboBoxAnimSelect;
    QLineEdit *inputStartCoords;
    QLineEdit *inputEntityNum;
    QPushButton *buttonClearOutput;
    QGroupBox *groupBoxTraversalDelta;
    QLabel *labelHorDelta;
    QLabel *labelVerDelta;
    QLabel *labelXDelta;
    QLabel *labelYDelta;
    QLabel *labelValXDelta;
    QLabel *labelValYDelta;
    QLabel *labelValHorDelta;
    QLabel *labelValVerDelta;
    QWidget *tab_2;
    QPushButton *buttonClearCoordsAndAnims;
    QLineEdit *inputEndCoordsChain;
    QPushButton *buttonClearOutputChain;
    QGroupBox *groupBoxMonsterSelect_3;
    QCheckBox *demonSelect_15_Chain;
    QLabel *labelMonsterType_Heavy_4;
    QCheckBox *demonSelect_18_Chain;
    QCheckBox *demonSelect_14_Chain;
    QCheckBox *demonSelect_17_Chain;
    QCheckBox *demonSelect_12_Chain;
    QCheckBox *demonSelect_7_Chain;
    QCheckBox *demonSelect_19_Chain;
    QCheckBox *demonSelect_9_Chain;
    QCheckBox *demonSelect_3_Chain;
    QLabel *labelMonsterType_SHeavy_4;
    QCheckBox *demonSelect_10_Chain;
    QCheckBox *demonSelect_5_Chain;
    QCheckBox *demonSelect_21_Chain;
    QCheckBox *demonSelect_16_Chain;
    QCheckBox *demonSelect_13_Chain;
    QCheckBox *demonSelect_8_Chain;
    QCheckBox *demonSelect_22_Chain;
    QCheckBox *demonSelect_2_Chain;
    QCheckBox *demonSelect_1_Chain;
    QLabel *labelMonsterType_Fodder_4;
    QCheckBox *demonSelect_20_Chain;
    QCheckBox *demonSelect_6_Chain;
    QCheckBox *demonSelect_4_Chain;
    QCheckBox *demonSelect_11_Chain;
    QLabel *labelMonsterTypeHeader_3;
    QLabel *labelMonsterTypePresetChain;
    QRadioButton *radioButtonPresetFodderChain;
    QRadioButton *radioButtonPresetHeavyChain;
    QRadioButton *radioButtonPresetSuperHeavyChain;
    QRadioButton *radioButtonPresetNoneChain;
    QRadioButton *radioButtonPresetAChain;
    QRadioButton *radioButtonPresetBChain;
    QRadioButton *radioButtonPresetCChain;
    QRadioButton *radioButtonPresetDChain;
    QLineEdit *inputStartCoordsChain;
    QPushButton *buttonGenerateTraversalChain;
    QComboBox *comboBoxAnimSelectStartChain;
    QCheckBox *selectReciprocalTraversalChain;
    QLineEdit *inputEntityNumChain;
    QLineEdit *inputMidCoordsChain;
    QLabel *labelStartAnimSelect;
    QLabel *labelMidAnimSelect;
    QComboBox *comboBoxAnimSelectStartChain_2;
    QPushButton *pushButtonAddMidpoint;
    QLabel *labelCurrentMidPoints;
    QListWidget *listWidgetMidpoints;
    QListWidget *listWidgetMidAnims;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(741, 712);
        QIcon icon;
        icon.addFile(QString::fromUtf8("praetor_dexterity_on_btP_icon.ico"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        tabWidgetTraversalEntityTypes = new QTabWidget(centralwidget);
        tabWidgetTraversalEntityTypes->setObjectName(QString::fromUtf8("tabWidgetTraversalEntityTypes"));
        tabWidgetTraversalEntityTypes->setGeometry(QRect(0, 0, 741, 711));
        tabWidgetTraversalEntityTypes->setLayoutDirection(Qt::LeftToRight);
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        inputEndCoords = new QLineEdit(tab);
        inputEndCoords->setObjectName(QString::fromUtf8("inputEndCoords"));
        inputEndCoords->setGeometry(QRect(30, 130, 321, 31));
        buttonClearCoords = new QPushButton(tab);
        buttonClearCoords->setObjectName(QString::fromUtf8("buttonClearCoords"));
        buttonClearCoords->setGeometry(QRect(30, 520, 321, 61));
        labelAnimTypeHeader = new QLabel(tab);
        labelAnimTypeHeader->setObjectName(QString::fromUtf8("labelAnimTypeHeader"));
        labelAnimTypeHeader->setGeometry(QRect(50, 50, 161, 31));
        labelAnimTypeHeader->setLineWidth(0);
        labelAnimTypeHeader->setTextFormat(Qt::MarkdownText);
        selectReciprocalTraversal = new QCheckBox(tab);
        selectReciprocalTraversal->setObjectName(QString::fromUtf8("selectReciprocalTraversal"));
        selectReciprocalTraversal->setGeometry(QRect(480, 630, 151, 31));
        buttonGenerateTraversal = new QPushButton(tab);
        buttonGenerateTraversal->setObjectName(QString::fromUtf8("buttonGenerateTraversal"));
        buttonGenerateTraversal->setGeometry(QRect(490, 540, 131, 81));
        groupBoxMonsterSelect = new QGroupBox(tab);
        groupBoxMonsterSelect->setObjectName(QString::fromUtf8("groupBoxMonsterSelect"));
        groupBoxMonsterSelect->setGeometry(QRect(390, 80, 311, 441));
        demonSelect_15 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_15->setObjectName(QString::fromUtf8("demonSelect_15"));
        demonSelect_15->setGeometry(QRect(220, 130, 81, 31));
        labelMonsterType_Heavy = new QLabel(groupBoxMonsterSelect);
        labelMonsterType_Heavy->setObjectName(QString::fromUtf8("labelMonsterType_Heavy"));
        labelMonsterType_Heavy->setGeometry(QRect(120, 10, 41, 31));
        labelMonsterType_Heavy->setLineWidth(0);
        labelMonsterType_Heavy->setTextFormat(Qt::MarkdownText);
        demonSelect_18 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_18->setObjectName(QString::fromUtf8("demonSelect_18"));
        demonSelect_18->setGeometry(QRect(120, 110, 81, 31));
        demonSelect_14 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_14->setObjectName(QString::fromUtf8("demonSelect_14"));
        demonSelect_14->setGeometry(QRect(120, 30, 81, 31));
        demonSelect_17 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_17->setObjectName(QString::fromUtf8("demonSelect_17"));
        demonSelect_17->setGeometry(QRect(220, 50, 81, 31));
        demonSelect_12 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_12->setObjectName(QString::fromUtf8("demonSelect_12"));
        demonSelect_12->setGeometry(QRect(10, 70, 81, 31));
        demonSelect_7 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_7->setObjectName(QString::fromUtf8("demonSelect_7"));
        demonSelect_7->setGeometry(QRect(220, 90, 81, 31));
        demonSelect_19 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_19->setObjectName(QString::fromUtf8("demonSelect_19"));
        demonSelect_19->setGeometry(QRect(10, 50, 81, 31));
        demonSelect_9 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_9->setObjectName(QString::fromUtf8("demonSelect_9"));
        demonSelect_9->setGeometry(QRect(120, 190, 81, 31));
        demonSelect_3 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_3->setObjectName(QString::fromUtf8("demonSelect_3"));
        demonSelect_3->setGeometry(QRect(120, 70, 81, 31));
        labelMonsterType_SHeavy = new QLabel(groupBoxMonsterSelect);
        labelMonsterType_SHeavy->setObjectName(QString::fromUtf8("labelMonsterType_SHeavy"));
        labelMonsterType_SHeavy->setGeometry(QRect(220, 10, 71, 31));
        labelMonsterType_SHeavy->setLineWidth(0);
        labelMonsterType_SHeavy->setTextFormat(Qt::MarkdownText);
        demonSelect_10 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_10->setObjectName(QString::fromUtf8("demonSelect_10"));
        demonSelect_10->setGeometry(QRect(220, 110, 81, 31));
        demonSelect_5 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_5->setObjectName(QString::fromUtf8("demonSelect_5"));
        demonSelect_5->setGeometry(QRect(120, 90, 81, 31));
        demonSelect_21 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_21->setObjectName(QString::fromUtf8("demonSelect_21"));
        demonSelect_21->setGeometry(QRect(120, 150, 81, 31));
        demonSelect_16 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_16->setObjectName(QString::fromUtf8("demonSelect_16"));
        demonSelect_16->setGeometry(QRect(10, 130, 81, 31));
        demonSelect_13 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_13->setObjectName(QString::fromUtf8("demonSelect_13"));
        demonSelect_13->setGeometry(QRect(10, 90, 91, 31));
        demonSelect_8 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_8->setObjectName(QString::fromUtf8("demonSelect_8"));
        demonSelect_8->setGeometry(QRect(120, 170, 81, 31));
        demonSelect_22 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_22->setObjectName(QString::fromUtf8("demonSelect_22"));
        demonSelect_22->setGeometry(QRect(10, 110, 81, 31));
        demonSelect_2 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_2->setObjectName(QString::fromUtf8("demonSelect_2"));
        demonSelect_2->setGeometry(QRect(120, 50, 81, 31));
        demonSelect_1 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_1->setObjectName(QString::fromUtf8("demonSelect_1"));
        demonSelect_1->setGeometry(QRect(220, 30, 81, 31));
        labelMonsterType_Fodder = new QLabel(groupBoxMonsterSelect);
        labelMonsterType_Fodder->setObjectName(QString::fromUtf8("labelMonsterType_Fodder"));
        labelMonsterType_Fodder->setGeometry(QRect(10, 10, 41, 31));
        labelMonsterType_Fodder->setLineWidth(0);
        labelMonsterType_Fodder->setTextFormat(Qt::MarkdownText);
        demonSelect_20 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_20->setObjectName(QString::fromUtf8("demonSelect_20"));
        demonSelect_20->setGeometry(QRect(120, 130, 81, 31));
        demonSelect_6 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_6->setObjectName(QString::fromUtf8("demonSelect_6"));
        demonSelect_6->setGeometry(QRect(10, 30, 81, 31));
        demonSelect_4 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_4->setObjectName(QString::fromUtf8("demonSelect_4"));
        demonSelect_4->setGeometry(QRect(220, 70, 81, 31));
        demonSelect_11 = new QCheckBox(groupBoxMonsterSelect);
        demonSelect_11->setObjectName(QString::fromUtf8("demonSelect_11"));
        demonSelect_11->setGeometry(QRect(120, 210, 81, 31));
        labelMonsterTypeHeader = new QLabel(groupBoxMonsterSelect);
        labelMonsterTypeHeader->setObjectName(QString::fromUtf8("labelMonsterTypeHeader"));
        labelMonsterTypeHeader->setGeometry(QRect(10, -10, 151, 31));
        labelMonsterTypeHeader->setLineWidth(0);
        labelMonsterTypeHeader->setTextFormat(Qt::MarkdownText);
        labelMonsterTypePresetInfo = new QLabel(groupBoxMonsterSelect);
        labelMonsterTypePresetInfo->setObjectName(QString::fromUtf8("labelMonsterTypePresetInfo"));
        labelMonsterTypePresetInfo->setGeometry(QRect(10, 250, 171, 31));
        labelMonsterTypePresetInfo->setLineWidth(0);
        labelMonsterTypePresetInfo->setTextFormat(Qt::MarkdownText);
        radioButtonPresetAInfo = new QRadioButton(groupBoxMonsterSelect);
        radioButtonPresetAInfo->setObjectName(QString::fromUtf8("radioButtonPresetAInfo"));
        radioButtonPresetAInfo->setGeometry(QRect(20, 360, 261, 17));
        radioButtonPresetSuperHeavyInfo = new QRadioButton(groupBoxMonsterSelect);
        radioButtonPresetSuperHeavyInfo->setObjectName(QString::fromUtf8("radioButtonPresetSuperHeavyInfo"));
        radioButtonPresetSuperHeavyInfo->setGeometry(QRect(20, 340, 91, 17));
        radioButtonPresetFodderInfo = new QRadioButton(groupBoxMonsterSelect);
        radioButtonPresetFodderInfo->setObjectName(QString::fromUtf8("radioButtonPresetFodderInfo"));
        radioButtonPresetFodderInfo->setGeometry(QRect(20, 300, 82, 17));
        radioButtonPresetCInfo = new QRadioButton(groupBoxMonsterSelect);
        radioButtonPresetCInfo->setObjectName(QString::fromUtf8("radioButtonPresetCInfo"));
        radioButtonPresetCInfo->setGeometry(QRect(20, 420, 261, 17));
        radioButtonPresetHeavyInfo = new QRadioButton(groupBoxMonsterSelect);
        radioButtonPresetHeavyInfo->setObjectName(QString::fromUtf8("radioButtonPresetHeavyInfo"));
        radioButtonPresetHeavyInfo->setGeometry(QRect(20, 320, 82, 17));
        radioButtonPresetNoneInfo = new QRadioButton(groupBoxMonsterSelect);
        radioButtonPresetNoneInfo->setObjectName(QString::fromUtf8("radioButtonPresetNoneInfo"));
        radioButtonPresetNoneInfo->setGeometry(QRect(20, 280, 82, 17));
        radioButtonPresetBInfo = new QRadioButton(groupBoxMonsterSelect);
        radioButtonPresetBInfo->setObjectName(QString::fromUtf8("radioButtonPresetBInfo"));
        radioButtonPresetBInfo->setGeometry(QRect(20, 400, 261, 17));
        radioButtonPresetDInfo = new QRadioButton(groupBoxMonsterSelect);
        radioButtonPresetDInfo->setObjectName(QString::fromUtf8("radioButtonPresetDInfo"));
        radioButtonPresetDInfo->setGeometry(QRect(20, 380, 261, 17));
        comboBoxAnimSelect = new QComboBox(tab);
        comboBoxAnimSelect->setObjectName(QString::fromUtf8("comboBoxAnimSelect"));
        comboBoxAnimSelect->setGeometry(QRect(50, 80, 191, 22));
        comboBoxAnimSelect->setMaxVisibleItems(45);
        inputStartCoords = new QLineEdit(tab);
        inputStartCoords->setObjectName(QString::fromUtf8("inputStartCoords"));
        inputStartCoords->setGeometry(QRect(30, 20, 321, 31));
        inputEntityNum = new QLineEdit(tab);
        inputEntityNum->setObjectName(QString::fromUtf8("inputEntityNum"));
        inputEntityNum->setGeometry(QRect(390, 20, 121, 31));
        buttonClearOutput = new QPushButton(tab);
        buttonClearOutput->setObjectName(QString::fromUtf8("buttonClearOutput"));
        buttonClearOutput->setGeometry(QRect(30, 600, 321, 61));
        groupBoxTraversalDelta = new QGroupBox(tab);
        groupBoxTraversalDelta->setObjectName(QString::fromUtf8("groupBoxTraversalDelta"));
        groupBoxTraversalDelta->setGeometry(QRect(50, 180, 131, 111));
        labelHorDelta = new QLabel(groupBoxTraversalDelta);
        labelHorDelta->setObjectName(QString::fromUtf8("labelHorDelta"));
        labelHorDelta->setGeometry(QRect(10, 70, 61, 16));
        labelVerDelta = new QLabel(groupBoxTraversalDelta);
        labelVerDelta->setObjectName(QString::fromUtf8("labelVerDelta"));
        labelVerDelta->setGeometry(QRect(10, 90, 41, 16));
        labelXDelta = new QLabel(groupBoxTraversalDelta);
        labelXDelta->setObjectName(QString::fromUtf8("labelXDelta"));
        labelXDelta->setGeometry(QRect(10, 20, 31, 16));
        labelYDelta = new QLabel(groupBoxTraversalDelta);
        labelYDelta->setObjectName(QString::fromUtf8("labelYDelta"));
        labelYDelta->setGeometry(QRect(10, 40, 31, 16));
        labelValXDelta = new QLabel(groupBoxTraversalDelta);
        labelValXDelta->setObjectName(QString::fromUtf8("labelValXDelta"));
        labelValXDelta->setGeometry(QRect(80, 20, 41, 16));
        labelValXDelta->setLayoutDirection(Qt::LeftToRight);
        labelValXDelta->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelValYDelta = new QLabel(groupBoxTraversalDelta);
        labelValYDelta->setObjectName(QString::fromUtf8("labelValYDelta"));
        labelValYDelta->setGeometry(QRect(80, 40, 41, 16));
        labelValYDelta->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelValHorDelta = new QLabel(groupBoxTraversalDelta);
        labelValHorDelta->setObjectName(QString::fromUtf8("labelValHorDelta"));
        labelValHorDelta->setGeometry(QRect(80, 70, 41, 16));
        labelValHorDelta->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelValVerDelta = new QLabel(groupBoxTraversalDelta);
        labelValVerDelta->setObjectName(QString::fromUtf8("labelValVerDelta"));
        labelValVerDelta->setGeometry(QRect(80, 90, 41, 16));
        labelValVerDelta->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tabWidgetTraversalEntityTypes->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        buttonClearCoordsAndAnims = new QPushButton(tab_2);
        buttonClearCoordsAndAnims->setObjectName(QString::fromUtf8("buttonClearCoordsAndAnims"));
        buttonClearCoordsAndAnims->setGeometry(QRect(30, 520, 321, 61));
        inputEndCoordsChain = new QLineEdit(tab_2);
        inputEndCoordsChain->setObjectName(QString::fromUtf8("inputEndCoordsChain"));
        inputEndCoordsChain->setGeometry(QRect(30, 460, 321, 31));
        buttonClearOutputChain = new QPushButton(tab_2);
        buttonClearOutputChain->setObjectName(QString::fromUtf8("buttonClearOutputChain"));
        buttonClearOutputChain->setGeometry(QRect(30, 600, 321, 61));
        groupBoxMonsterSelect_3 = new QGroupBox(tab_2);
        groupBoxMonsterSelect_3->setObjectName(QString::fromUtf8("groupBoxMonsterSelect_3"));
        groupBoxMonsterSelect_3->setGeometry(QRect(390, 80, 311, 441));
        demonSelect_15_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_15_Chain->setObjectName(QString::fromUtf8("demonSelect_15_Chain"));
        demonSelect_15_Chain->setGeometry(QRect(220, 130, 81, 31));
        labelMonsterType_Heavy_4 = new QLabel(groupBoxMonsterSelect_3);
        labelMonsterType_Heavy_4->setObjectName(QString::fromUtf8("labelMonsterType_Heavy_4"));
        labelMonsterType_Heavy_4->setGeometry(QRect(120, 10, 41, 31));
        labelMonsterType_Heavy_4->setLineWidth(0);
        labelMonsterType_Heavy_4->setTextFormat(Qt::MarkdownText);
        demonSelect_18_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_18_Chain->setObjectName(QString::fromUtf8("demonSelect_18_Chain"));
        demonSelect_18_Chain->setGeometry(QRect(120, 110, 81, 31));
        demonSelect_14_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_14_Chain->setObjectName(QString::fromUtf8("demonSelect_14_Chain"));
        demonSelect_14_Chain->setGeometry(QRect(120, 30, 81, 31));
        demonSelect_17_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_17_Chain->setObjectName(QString::fromUtf8("demonSelect_17_Chain"));
        demonSelect_17_Chain->setGeometry(QRect(220, 50, 81, 31));
        demonSelect_12_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_12_Chain->setObjectName(QString::fromUtf8("demonSelect_12_Chain"));
        demonSelect_12_Chain->setGeometry(QRect(10, 70, 81, 31));
        demonSelect_7_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_7_Chain->setObjectName(QString::fromUtf8("demonSelect_7_Chain"));
        demonSelect_7_Chain->setGeometry(QRect(220, 90, 81, 31));
        demonSelect_19_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_19_Chain->setObjectName(QString::fromUtf8("demonSelect_19_Chain"));
        demonSelect_19_Chain->setGeometry(QRect(10, 50, 81, 31));
        demonSelect_9_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_9_Chain->setObjectName(QString::fromUtf8("demonSelect_9_Chain"));
        demonSelect_9_Chain->setGeometry(QRect(120, 190, 81, 31));
        demonSelect_3_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_3_Chain->setObjectName(QString::fromUtf8("demonSelect_3_Chain"));
        demonSelect_3_Chain->setGeometry(QRect(120, 70, 81, 31));
        labelMonsterType_SHeavy_4 = new QLabel(groupBoxMonsterSelect_3);
        labelMonsterType_SHeavy_4->setObjectName(QString::fromUtf8("labelMonsterType_SHeavy_4"));
        labelMonsterType_SHeavy_4->setGeometry(QRect(220, 10, 71, 31));
        labelMonsterType_SHeavy_4->setLineWidth(0);
        labelMonsterType_SHeavy_4->setTextFormat(Qt::MarkdownText);
        demonSelect_10_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_10_Chain->setObjectName(QString::fromUtf8("demonSelect_10_Chain"));
        demonSelect_10_Chain->setGeometry(QRect(220, 110, 81, 31));
        demonSelect_5_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_5_Chain->setObjectName(QString::fromUtf8("demonSelect_5_Chain"));
        demonSelect_5_Chain->setGeometry(QRect(120, 90, 81, 31));
        demonSelect_21_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_21_Chain->setObjectName(QString::fromUtf8("demonSelect_21_Chain"));
        demonSelect_21_Chain->setGeometry(QRect(120, 150, 81, 31));
        demonSelect_16_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_16_Chain->setObjectName(QString::fromUtf8("demonSelect_16_Chain"));
        demonSelect_16_Chain->setGeometry(QRect(10, 130, 81, 31));
        demonSelect_13_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_13_Chain->setObjectName(QString::fromUtf8("demonSelect_13_Chain"));
        demonSelect_13_Chain->setGeometry(QRect(10, 90, 91, 31));
        demonSelect_8_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_8_Chain->setObjectName(QString::fromUtf8("demonSelect_8_Chain"));
        demonSelect_8_Chain->setGeometry(QRect(120, 170, 81, 31));
        demonSelect_22_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_22_Chain->setObjectName(QString::fromUtf8("demonSelect_22_Chain"));
        demonSelect_22_Chain->setGeometry(QRect(10, 110, 81, 31));
        demonSelect_2_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_2_Chain->setObjectName(QString::fromUtf8("demonSelect_2_Chain"));
        demonSelect_2_Chain->setGeometry(QRect(120, 50, 81, 31));
        demonSelect_1_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_1_Chain->setObjectName(QString::fromUtf8("demonSelect_1_Chain"));
        demonSelect_1_Chain->setGeometry(QRect(220, 30, 81, 31));
        labelMonsterType_Fodder_4 = new QLabel(groupBoxMonsterSelect_3);
        labelMonsterType_Fodder_4->setObjectName(QString::fromUtf8("labelMonsterType_Fodder_4"));
        labelMonsterType_Fodder_4->setGeometry(QRect(10, 10, 41, 31));
        labelMonsterType_Fodder_4->setLineWidth(0);
        labelMonsterType_Fodder_4->setTextFormat(Qt::MarkdownText);
        demonSelect_20_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_20_Chain->setObjectName(QString::fromUtf8("demonSelect_20_Chain"));
        demonSelect_20_Chain->setGeometry(QRect(120, 130, 81, 31));
        demonSelect_6_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_6_Chain->setObjectName(QString::fromUtf8("demonSelect_6_Chain"));
        demonSelect_6_Chain->setGeometry(QRect(10, 30, 81, 31));
        demonSelect_4_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_4_Chain->setObjectName(QString::fromUtf8("demonSelect_4_Chain"));
        demonSelect_4_Chain->setGeometry(QRect(220, 70, 81, 31));
        demonSelect_11_Chain = new QCheckBox(groupBoxMonsterSelect_3);
        demonSelect_11_Chain->setObjectName(QString::fromUtf8("demonSelect_11_Chain"));
        demonSelect_11_Chain->setGeometry(QRect(120, 210, 81, 31));
        labelMonsterTypeHeader_3 = new QLabel(groupBoxMonsterSelect_3);
        labelMonsterTypeHeader_3->setObjectName(QString::fromUtf8("labelMonsterTypeHeader_3"));
        labelMonsterTypeHeader_3->setGeometry(QRect(10, -10, 151, 31));
        labelMonsterTypeHeader_3->setLineWidth(0);
        labelMonsterTypeHeader_3->setTextFormat(Qt::MarkdownText);
        labelMonsterTypePresetChain = new QLabel(groupBoxMonsterSelect_3);
        labelMonsterTypePresetChain->setObjectName(QString::fromUtf8("labelMonsterTypePresetChain"));
        labelMonsterTypePresetChain->setGeometry(QRect(10, 250, 171, 31));
        labelMonsterTypePresetChain->setLineWidth(0);
        labelMonsterTypePresetChain->setTextFormat(Qt::MarkdownText);
        radioButtonPresetFodderChain = new QRadioButton(groupBoxMonsterSelect_3);
        radioButtonPresetFodderChain->setObjectName(QString::fromUtf8("radioButtonPresetFodderChain"));
        radioButtonPresetFodderChain->setGeometry(QRect(20, 300, 82, 17));
        radioButtonPresetHeavyChain = new QRadioButton(groupBoxMonsterSelect_3);
        radioButtonPresetHeavyChain->setObjectName(QString::fromUtf8("radioButtonPresetHeavyChain"));
        radioButtonPresetHeavyChain->setGeometry(QRect(20, 320, 82, 17));
        radioButtonPresetSuperHeavyChain = new QRadioButton(groupBoxMonsterSelect_3);
        radioButtonPresetSuperHeavyChain->setObjectName(QString::fromUtf8("radioButtonPresetSuperHeavyChain"));
        radioButtonPresetSuperHeavyChain->setGeometry(QRect(20, 340, 91, 17));
        radioButtonPresetNoneChain = new QRadioButton(groupBoxMonsterSelect_3);
        radioButtonPresetNoneChain->setObjectName(QString::fromUtf8("radioButtonPresetNoneChain"));
        radioButtonPresetNoneChain->setGeometry(QRect(20, 280, 82, 17));
        radioButtonPresetAChain = new QRadioButton(groupBoxMonsterSelect_3);
        radioButtonPresetAChain->setObjectName(QString::fromUtf8("radioButtonPresetAChain"));
        radioButtonPresetAChain->setGeometry(QRect(20, 360, 261, 17));
        radioButtonPresetBChain = new QRadioButton(groupBoxMonsterSelect_3);
        radioButtonPresetBChain->setObjectName(QString::fromUtf8("radioButtonPresetBChain"));
        radioButtonPresetBChain->setGeometry(QRect(20, 400, 261, 17));
        radioButtonPresetCChain = new QRadioButton(groupBoxMonsterSelect_3);
        radioButtonPresetCChain->setObjectName(QString::fromUtf8("radioButtonPresetCChain"));
        radioButtonPresetCChain->setGeometry(QRect(20, 420, 261, 17));
        radioButtonPresetDChain = new QRadioButton(groupBoxMonsterSelect_3);
        radioButtonPresetDChain->setObjectName(QString::fromUtf8("radioButtonPresetDChain"));
        radioButtonPresetDChain->setGeometry(QRect(20, 380, 261, 17));
        inputStartCoordsChain = new QLineEdit(tab_2);
        inputStartCoordsChain->setObjectName(QString::fromUtf8("inputStartCoordsChain"));
        inputStartCoordsChain->setGeometry(QRect(30, 20, 321, 31));
        buttonGenerateTraversalChain = new QPushButton(tab_2);
        buttonGenerateTraversalChain->setObjectName(QString::fromUtf8("buttonGenerateTraversalChain"));
        buttonGenerateTraversalChain->setGeometry(QRect(490, 540, 131, 81));
        comboBoxAnimSelectStartChain = new QComboBox(tab_2);
        comboBoxAnimSelectStartChain->setObjectName(QString::fromUtf8("comboBoxAnimSelectStartChain"));
        comboBoxAnimSelectStartChain->setGeometry(QRect(50, 80, 191, 22));
        comboBoxAnimSelectStartChain->setMaxVisibleItems(45);
        selectReciprocalTraversalChain = new QCheckBox(tab_2);
        selectReciprocalTraversalChain->setObjectName(QString::fromUtf8("selectReciprocalTraversalChain"));
        selectReciprocalTraversalChain->setGeometry(QRect(470, 630, 181, 31));
        inputEntityNumChain = new QLineEdit(tab_2);
        inputEntityNumChain->setObjectName(QString::fromUtf8("inputEntityNumChain"));
        inputEntityNumChain->setGeometry(QRect(390, 20, 121, 31));
        inputMidCoordsChain = new QLineEdit(tab_2);
        inputMidCoordsChain->setObjectName(QString::fromUtf8("inputMidCoordsChain"));
        inputMidCoordsChain->setGeometry(QRect(30, 130, 321, 31));
        labelStartAnimSelect = new QLabel(tab_2);
        labelStartAnimSelect->setObjectName(QString::fromUtf8("labelStartAnimSelect"));
        labelStartAnimSelect->setGeometry(QRect(50, 50, 161, 31));
        labelMidAnimSelect = new QLabel(tab_2);
        labelMidAnimSelect->setObjectName(QString::fromUtf8("labelMidAnimSelect"));
        labelMidAnimSelect->setGeometry(QRect(50, 160, 221, 31));
        comboBoxAnimSelectStartChain_2 = new QComboBox(tab_2);
        comboBoxAnimSelectStartChain_2->setObjectName(QString::fromUtf8("comboBoxAnimSelectStartChain_2"));
        comboBoxAnimSelectStartChain_2->setGeometry(QRect(50, 190, 191, 22));
        comboBoxAnimSelectStartChain_2->setMaxVisibleItems(45);
        pushButtonAddMidpoint = new QPushButton(tab_2);
        pushButtonAddMidpoint->setObjectName(QString::fromUtf8("pushButtonAddMidpoint"));
        pushButtonAddMidpoint->setGeometry(QRect(280, 170, 71, 61));
        labelCurrentMidPoints = new QLabel(tab_2);
        labelCurrentMidPoints->setObjectName(QString::fromUtf8("labelCurrentMidPoints"));
        labelCurrentMidPoints->setGeometry(QRect(50, 210, 91, 31));
        listWidgetMidpoints = new QListWidget(tab_2);
        listWidgetMidpoints->setObjectName(QString::fromUtf8("listWidgetMidpoints"));
        listWidgetMidpoints->setGeometry(QRect(50, 240, 161, 192));
        listWidgetMidAnims = new QListWidget(tab_2);
        listWidgetMidAnims->setObjectName(QString::fromUtf8("listWidgetMidAnims"));
        listWidgetMidAnims->setGeometry(QRect(220, 240, 131, 192));
        tabWidgetTraversalEntityTypes->addTab(tab_2, QString());
        MainWindow->setCentralWidget(centralwidget);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        tabWidgetTraversalEntityTypes->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "TraversalMaykr-Py-GUI v0.1", nullptr));
        inputEndCoords->setPlaceholderText(QCoreApplication::translate("MainWindow", "Destination Coordiantes", nullptr));
        buttonClearCoords->setText(QCoreApplication::translate("MainWindow", "Clear Coordinates", nullptr));
        labelAnimTypeHeader->setText(QCoreApplication::translate("MainWindow", "Select animation to Destination", nullptr));
        selectReciprocalTraversal->setText(QCoreApplication::translate("MainWindow", "Create reciprocal traversal", nullptr));
        buttonGenerateTraversal->setText(QCoreApplication::translate("MainWindow", "Generate Traversals", nullptr));
        groupBoxMonsterSelect->setTitle(QString());
        demonSelect_15->setText(QCoreApplication::translate("MainWindow", "Wolf", nullptr));
        labelMonsterType_Heavy->setText(QCoreApplication::translate("MainWindow", "Heavy", nullptr));
        demonSelect_18->setText(QCoreApplication::translate("MainWindow", "Hell Knight", nullptr));
        demonSelect_14->setText(QCoreApplication::translate("MainWindow", "Arachnotron", nullptr));
        demonSelect_17->setText(QCoreApplication::translate("MainWindow", "Baron of Hell", nullptr));
        demonSelect_12->setText(QCoreApplication::translate("MainWindow", "Maykr Drone", nullptr));
        demonSelect_7->setText(QCoreApplication::translate("MainWindow", "Marauder", nullptr));
        demonSelect_19->setText(QCoreApplication::translate("MainWindow", "Imp", nullptr));
        demonSelect_9->setText(QCoreApplication::translate("MainWindow", "Revenant", nullptr));
        demonSelect_3->setText(QCoreApplication::translate("MainWindow", "Carcass", nullptr));
        labelMonsterType_SHeavy->setText(QCoreApplication::translate("MainWindow", "Super Heavy", nullptr));
        demonSelect_10->setText(QCoreApplication::translate("MainWindow", "Tyrant", nullptr));
        demonSelect_5->setText(QCoreApplication::translate("MainWindow", "Dread Knight", nullptr));
        demonSelect_21->setText(QCoreApplication::translate("MainWindow", "Pinky", nullptr));
        demonSelect_16->setText(QCoreApplication::translate("MainWindow", "Zombie", nullptr));
        demonSelect_13->setText(QCoreApplication::translate("MainWindow", "Mecha Zombie", nullptr));
        demonSelect_8->setText(QCoreApplication::translate("MainWindow", "Prowler", nullptr));
        demonSelect_22->setText(QCoreApplication::translate("MainWindow", "Soldier", nullptr));
        demonSelect_2->setText(QCoreApplication::translate("MainWindow", "Blood Maykr", nullptr));
        demonSelect_1->setText(QCoreApplication::translate("MainWindow", "Archvile", nullptr));
        labelMonsterType_Fodder->setText(QCoreApplication::translate("MainWindow", "Fodder", nullptr));
        demonSelect_20->setText(QCoreApplication::translate("MainWindow", "Mancubus", nullptr));
        demonSelect_6->setText(QCoreApplication::translate("MainWindow", "Gargoyle", nullptr));
        demonSelect_4->setText(QCoreApplication::translate("MainWindow", "Doom Hunter", nullptr));
        demonSelect_11->setText(QCoreApplication::translate("MainWindow", "Whiplash", nullptr));
        labelMonsterTypeHeader->setText(QCoreApplication::translate("MainWindow", "__**Monster Type Selection**__", nullptr));
        labelMonsterTypePresetInfo->setText(QCoreApplication::translate("MainWindow", "Presets (Ignores Above Selections)", nullptr));
        radioButtonPresetAInfo->setText(QCoreApplication::translate("MainWindow", "Fodder + Carcass, Prowler, Whiplash, Marauder", nullptr));
        radioButtonPresetSuperHeavyInfo->setText(QCoreApplication::translate("MainWindow", "Super Heavy", nullptr));
        radioButtonPresetFodderInfo->setText(QCoreApplication::translate("MainWindow", "Fodder", nullptr));
        radioButtonPresetCInfo->setText(QCoreApplication::translate("MainWindow", "All", nullptr));
        radioButtonPresetHeavyInfo->setText(QCoreApplication::translate("MainWindow", "Heavy", nullptr));
        radioButtonPresetNoneInfo->setText(QCoreApplication::translate("MainWindow", "None", nullptr));
        radioButtonPresetBInfo->setText(QCoreApplication::translate("MainWindow", "All sans Tyrant", nullptr));
        radioButtonPresetDInfo->setText(QCoreApplication::translate("MainWindow", "Thruster Assisted and Teleporting Demons", nullptr));
        inputStartCoords->setPlaceholderText(QCoreApplication::translate("MainWindow", "Start Coordinates", nullptr));
        inputEntityNum->setPlaceholderText(QCoreApplication::translate("MainWindow", "Starting Entity Number", nullptr));
        buttonClearOutput->setText(QCoreApplication::translate("MainWindow", "Clear Output File", nullptr));
        groupBoxTraversalDelta->setTitle(QCoreApplication::translate("MainWindow", "Delta Values", nullptr));
        labelHorDelta->setText(QCoreApplication::translate("MainWindow", "Horizontal :", nullptr));
        labelVerDelta->setText(QCoreApplication::translate("MainWindow", "Vertical :", nullptr));
        labelXDelta->setText(QCoreApplication::translate("MainWindow", "X :", nullptr));
        labelYDelta->setText(QCoreApplication::translate("MainWindow", "Y : ", nullptr));
        labelValXDelta->setText(QCoreApplication::translate("MainWindow", "0.0000", nullptr));
        labelValYDelta->setText(QCoreApplication::translate("MainWindow", "0.0000", nullptr));
        labelValHorDelta->setText(QCoreApplication::translate("MainWindow", "0.0000", nullptr));
        labelValVerDelta->setText(QCoreApplication::translate("MainWindow", "0.0000", nullptr));
        tabWidgetTraversalEntityTypes->setTabText(tabWidgetTraversalEntityTypes->indexOf(tab), QCoreApplication::translate("MainWindow", "Traversal Info", nullptr));
        buttonClearCoordsAndAnims->setText(QCoreApplication::translate("MainWindow", "Clear Coordinates and Midpoints", nullptr));
        inputEndCoordsChain->setPlaceholderText(QCoreApplication::translate("MainWindow", "Destination Coordiantes", nullptr));
        buttonClearOutputChain->setText(QCoreApplication::translate("MainWindow", "Clear Output File", nullptr));
        groupBoxMonsterSelect_3->setTitle(QString());
        demonSelect_15_Chain->setText(QCoreApplication::translate("MainWindow", "Wolf", nullptr));
        labelMonsterType_Heavy_4->setText(QCoreApplication::translate("MainWindow", "Heavy", nullptr));
        demonSelect_18_Chain->setText(QCoreApplication::translate("MainWindow", "Hell Knight", nullptr));
        demonSelect_14_Chain->setText(QCoreApplication::translate("MainWindow", "Arachnotron", nullptr));
        demonSelect_17_Chain->setText(QCoreApplication::translate("MainWindow", "Baron of Hell", nullptr));
        demonSelect_12_Chain->setText(QCoreApplication::translate("MainWindow", "Maykr Drone", nullptr));
        demonSelect_7_Chain->setText(QCoreApplication::translate("MainWindow", "Marauder", nullptr));
        demonSelect_19_Chain->setText(QCoreApplication::translate("MainWindow", "Imp", nullptr));
        demonSelect_9_Chain->setText(QCoreApplication::translate("MainWindow", "Revenant", nullptr));
        demonSelect_3_Chain->setText(QCoreApplication::translate("MainWindow", "Carcass", nullptr));
        labelMonsterType_SHeavy_4->setText(QCoreApplication::translate("MainWindow", "Super Heavy", nullptr));
        demonSelect_10_Chain->setText(QCoreApplication::translate("MainWindow", "Tyrant", nullptr));
        demonSelect_5_Chain->setText(QCoreApplication::translate("MainWindow", "Dread Knight", nullptr));
        demonSelect_21_Chain->setText(QCoreApplication::translate("MainWindow", "Pinky", nullptr));
        demonSelect_16_Chain->setText(QCoreApplication::translate("MainWindow", "Zombie", nullptr));
        demonSelect_13_Chain->setText(QCoreApplication::translate("MainWindow", "Mecha Zombie", nullptr));
        demonSelect_8_Chain->setText(QCoreApplication::translate("MainWindow", "Prowler", nullptr));
        demonSelect_22_Chain->setText(QCoreApplication::translate("MainWindow", "Soldier", nullptr));
        demonSelect_2_Chain->setText(QCoreApplication::translate("MainWindow", "Blood Maykr", nullptr));
        demonSelect_1_Chain->setText(QCoreApplication::translate("MainWindow", "Archvile", nullptr));
        labelMonsterType_Fodder_4->setText(QCoreApplication::translate("MainWindow", "Fodder", nullptr));
        demonSelect_20_Chain->setText(QCoreApplication::translate("MainWindow", "Mancubus", nullptr));
        demonSelect_6_Chain->setText(QCoreApplication::translate("MainWindow", "Gargoyle", nullptr));
        demonSelect_4_Chain->setText(QCoreApplication::translate("MainWindow", "Doom Hunter", nullptr));
        demonSelect_11_Chain->setText(QCoreApplication::translate("MainWindow", "Whiplash", nullptr));
        labelMonsterTypeHeader_3->setText(QCoreApplication::translate("MainWindow", "__**Monster Type Selection**__", nullptr));
        labelMonsterTypePresetChain->setText(QCoreApplication::translate("MainWindow", "Presets (Ignores Above Selections)", nullptr));
        radioButtonPresetFodderChain->setText(QCoreApplication::translate("MainWindow", "Fodder", nullptr));
        radioButtonPresetHeavyChain->setText(QCoreApplication::translate("MainWindow", "Heavy", nullptr));
        radioButtonPresetSuperHeavyChain->setText(QCoreApplication::translate("MainWindow", "Super Heavy", nullptr));
        radioButtonPresetNoneChain->setText(QCoreApplication::translate("MainWindow", "None", nullptr));
        radioButtonPresetAChain->setText(QCoreApplication::translate("MainWindow", "Fodder + Carcass, Prowler, Whiplash, Marauder", nullptr));
        radioButtonPresetBChain->setText(QCoreApplication::translate("MainWindow", "All sans Tyrant", nullptr));
        radioButtonPresetCChain->setText(QCoreApplication::translate("MainWindow", "All", nullptr));
        radioButtonPresetDChain->setText(QCoreApplication::translate("MainWindow", "Thruster Assisted and Teleporting Demons", nullptr));
        inputStartCoordsChain->setPlaceholderText(QCoreApplication::translate("MainWindow", "Start Coordinates", nullptr));
        buttonGenerateTraversalChain->setText(QCoreApplication::translate("MainWindow", "Generate Traversal Chain", nullptr));
        comboBoxAnimSelectStartChain->setPlaceholderText(QString());
        selectReciprocalTraversalChain->setText(QCoreApplication::translate("MainWindow", "Create reciprocal traversal chain", nullptr));
        inputEntityNumChain->setPlaceholderText(QCoreApplication::translate("MainWindow", "Starting Entity Number", nullptr));
        inputMidCoordsChain->setText(QString());
        inputMidCoordsChain->setPlaceholderText(QCoreApplication::translate("MainWindow", "Midpoint Coordinates", nullptr));
        labelStartAnimSelect->setText(QCoreApplication::translate("MainWindow", "Select animation to first midpoint", nullptr));
        labelMidAnimSelect->setText(QCoreApplication::translate("MainWindow", "Select animation to next midpoint/destination", nullptr));
        comboBoxAnimSelectStartChain_2->setPlaceholderText(QString());
        pushButtonAddMidpoint->setText(QCoreApplication::translate("MainWindow", "Add Midpoint", nullptr));
        labelCurrentMidPoints->setText(QCoreApplication::translate("MainWindow", "Current Midpoints", nullptr));
        tabWidgetTraversalEntityTypes->setTabText(tabWidgetTraversalEntityTypes->indexOf(tab_2), QCoreApplication::translate("MainWindow", "Traversal Chain", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
